# Generated by Django 6.0.2 on 2026-02-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('moneda_codigo', models.CharField(max_length=3)),
                ('moneda_nombre', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('ANDINA', 'ANDINA'), ('CONO_SUR', 'CONO_SUR'), ('CENTROAMERICA', 'CENTROAMERICA'), ('CARIBE', 'CARIBE')], max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('poblacion', models.BigIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(max_length=3)),
                ('moneda_destino', models.CharField(default='USD', max_length=3)),
                ('tasa', models.FloatField()),
                ('fecha', models.DateField()),
                ('variacion_porcentual', models.FloatField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, default='MANUAL', max_length=50)),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('moneda_origen', 'moneda_destino', 'fecha'), name='uniq_fx_pair_fecha')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIB', 'PIB'), ('INFLACION', 'INFLACION'), ('DESEMPLEO', 'DESEMPLEO'), ('BALANZA_COMERCIAL', 'BALANZA_COMERCIAL'), ('DEUDA_PIB', 'DEUDA_PIB'), ('PIB_PERCAPITA', 'PIB_PERCAPITA')], max_length=30)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(choices=[('PORCENTAJE', 'PORCENTAJE'), ('USD', 'USD'), ('USD_MILES_MILLONES', 'USD_MILES_MILLONES')], max_length=30)),
                ('anio', models.PositiveIntegerField()),
                ('fuente', models.CharField(choices=[('WORLD_BANK', 'WORLD_BANK'), ('MANUAL', 'MANUAL')], default='MANUAL', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='api.pais')),
            ],
            options={
                'ordering': ['-anio'],
                'constraints': [models.UniqueConstraint(fields=('pais', 'tipo', 'anio'), name='uniq_indicador_pais_tipo_anio')],
            },
        ),
    ]
