# Generated by Django 6.0.2 on 2026-02-16 23:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pais_tipocambio_indicadoreconomico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portafolios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=120)),
                ('ticker', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_activo', models.CharField(blank=True, default='', max_length=60)),
                ('moneda', models.CharField(blank=True, default='USD', max_length=3)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-07)])),
                ('precio_unitario', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('peso_porcentual', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posiciones', to='api.pais')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='api.portafolio')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('portafolio', 'pais', 'activo', 'ticker'), name='uniq_posicion_portafolio_pais_activo_ticker')],
            },
        ),
    ]
