# Generated by Django 6.0.2 on 2026-02-17 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portafolio_posicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posicion',
            name='uniq_posicion_portafolio_pais_activo_ticker',
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portafolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='moneda',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='peso_porcentual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='ticker',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tipo_activo',
            field=models.CharField(choices=[('ACCION', 'ACCION'), ('BONO', 'BONO'), ('ETF', 'ETF'), ('CRYPTO', 'CRYPTO'), ('OTRO', 'OTRO')], default='ACCION', max_length=20),
        ),
    ]
