# Generated by Django 6.0.2 on 2026-02-17 06:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_posicion_uniq_posicion_portafolio_pais_activo_ticker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('RIESGO', 'RIESGO'), ('TIPO_CAMBIO', 'TIPO_CAMBIO'), ('INDICADOR', 'INDICADOR')], max_length=20)),
                ('severidad', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='IndiceRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.now)),
                ('score_economico', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_cambiario', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_estabilidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('indice_compuesto', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'BAJO'), ('MODERADO', 'MODERADO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], max_length=12)),
                ('detalle_calculo', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_calculo', 'pais__nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'CREAR'), ('EDITAR', 'EDITAR'), ('ELIMINAR', 'ELIMINAR'), ('CONSULTAR', 'CONSULTAR'), ('LOGIN', 'LOGIN'), ('EXPORT', 'EXPORT')], max_length=20)),
                ('entidad_afectada', models.CharField(max_length=80)),
                ('entidad_id', models.CharField(blank=True, max_length=64)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='portafolio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posicion',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='monto_inversion_usd',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='posicion',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tipo_activo',
            field=models.CharField(choices=[('RENTA_FIJA', 'RENTA_FIJA'), ('RENTA_VARIABLE', 'RENTA_VARIABLE'), ('COMMODITIES', 'COMMODITIES'), ('MONEDA', 'MONEDA'), ('ACCION', 'ACCION'), ('BONO', 'BONO'), ('ETF', 'ETF'), ('CRYPTO', 'CRYPTO'), ('OTRO', 'OTRO')], default='ACCION', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='portafolio',
            constraint=models.UniqueConstraint(fields=('owner', 'nombre'), name='uniq_owner_portafolio_nombre_activo'),
        ),
        migrations.AddConstraint(
            model_name='posicion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_salida__isnull', True), ('fecha_salida__gt', models.F('fecha_entrada')), _connector='OR'), name='posicion_fecha_salida_gt_entrada'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.pais'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indiceriesgo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices_riesgo', to='api.pais'),
        ),
        migrations.AddField(
            model_name='logactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='indiceriesgo',
            constraint=models.UniqueConstraint(fields=('pais', 'fecha_calculo'), name='uniq_riesgo_pais_fecha'),
        ),
    ]
