# Generated by Django 6.0.2 on 2026-02-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alerta_indiceriesgo_logactividad_portafolio_activo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
