# Generated by Django 6.0.2 on 2026-02-17 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_contactmessage_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['usuario', 'leida'], name='api_alerta_usuario_29ca85_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo_alerta', 'severidad'], name='api_alerta_tipo_al_662fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['fecha_creacion'], name='api_alerta_fecha_c_f04a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='indicadoreconomico',
            index=models.Index(fields=['pais', 'tipo', 'anio'], name='api_indicad_pais_id_096d47_idx'),
        ),
        migrations.AddIndex(
            model_name='indicadoreconomico',
            index=models.Index(fields=['tipo', 'anio'], name='api_indicad_tipo_8dcb70_idx'),
        ),
        migrations.AddIndex(
            model_name='indiceriesgo',
            index=models.Index(fields=['pais', 'fecha_calculo'], name='api_indicer_pais_id_c793fe_idx'),
        ),
        migrations.AddIndex(
            model_name='indiceriesgo',
            index=models.Index(fields=['indice_compuesto'], name='api_indicer_indice__7c98b5_idx'),
        ),
        migrations.AddIndex(
            model_name='logactividad',
            index=models.Index(fields=['usuario', 'fecha'], name='api_logacti_usuario_1dbab1_idx'),
        ),
        migrations.AddIndex(
            model_name='logactividad',
            index=models.Index(fields=['accion', 'fecha'], name='api_logacti_accion_5c6543_idx'),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['codigo_iso'], name='api_pais_codigo__43970a_idx'),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['region'], name='api_pais_region_2281b5_idx'),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['nombre'], name='api_pais_nombre_ba9664_idx'),
        ),
        migrations.AddIndex(
            model_name='portafolio',
            index=models.Index(fields=['owner', 'activo'], name='api_portafo_owner_i_d7f41c_idx'),
        ),
        migrations.AddIndex(
            model_name='portafolio',
            index=models.Index(fields=['es_publico', 'activo'], name='api_portafo_es_publ_766d24_idx'),
        ),
        migrations.AddIndex(
            model_name='portafolio',
            index=models.Index(fields=['nombre'], name='api_portafo_nombre_67fdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='posicion',
            index=models.Index(fields=['portafolio', 'pais', 'tipo_activo'], name='api_posicio_portafo_83a7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='posicion',
            index=models.Index(fields=['fecha_salida'], name='api_posicio_fecha_s_0d7e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocambio',
            index=models.Index(fields=['moneda_origen', 'fecha'], name='api_tipocam_moneda__1ede3f_idx'),
        ),
    ]
